In [110]:
import tensorflow as tf

physical_devices = tf.config.list_physical_devices('GPU')
if physical_devices:
    try:
        tf.config.experimental.set_memory_growth(physical_devices[0], True)
    except RuntimeError as e:
        print(e)
print("Num GPUs Available: ", len(tf.config.list_physical_devices('GPU')))
print(tf.__version__)


Num GPUs Available:  1
2.10.0


### Creatting tensors with `tf.Variable`

In [111]:
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])

changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7])>)

In [112]:
changeable_tensor.assign_add(unchangeable_tensor)
print(changeable_tensor)


<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([20, 14])>


In [113]:
# unchangeable_tensor[0].assign(2)
# print(unchangeable_tensor)
#AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

### Creating Random tensors

In [114]:
random_1 = tf.random.Generator.from_seed(42)  # set seed for reproducibility
random_1 = random_1.normal(shape=(3, 2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3, 2))

random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

### Shuffle order of elements in a tensor

In [115]:
not_shuffled = tf.constant([[10, 7],
                            [3, 2],
                            [9, 3]])

not_shuffled2 = tf.constant([[40, 74],
                             [13, 21],
                             [22, 81]])

not_shuffled3 = tf.constant([[520, 517],
                             [226, 315],
                             [431, 244]])

not_shuffled, not_shuffled2, not_shuffled3

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  2],
        [ 9,  3]])>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[40, 74],
        [13, 21],
        [22, 81]])>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[520, 517],
        [226, 315],
        [431, 244]])>)

In [116]:
tf.random.set_seed(42)
print(tf.random.shuffle(not_shuffled))
print(tf.random.shuffle(not_shuffled))
print(tf.random.shuffle(not_shuffled))

# Notice that operator seed and general seed need to be combined to get the same result



tf.Tensor(
[[ 3  2]
 [ 9  3]
 [10  7]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[ 9  3]
 [10  7]
 [ 3  2]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[ 9  3]
 [ 3  2]
 [10  7]], shape=(3, 2), dtype=int32)


### Other ways to create tensors (Numpy)

In [117]:
#  Different types of arrays
# X= tf.ones((3,3))
# X= tf.zeros((3,3))
X = tf.eye((3))
X

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)>

#### Turn NumPy arrays into tensors

The main difference is that tensors can be run  in GPU (faster computing).

In [118]:
import numpy as np

np_array = np.arange(1, 25, dtype=np.int32)

print(np_array)

tf_array = tf.constant(np_array)  # pass the np_array as a value
tf_array

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])>

In [119]:
A = tf.constant(np_array, shape=(2, 3, 4))  # 2x3x4 = 24
B = tf.constant(np_array)
print(f'A matrix dimension = {A.ndim}')
A, B

A matrix dimension = 3


(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]])>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24])>)

## Get more informations from our tensors

When dealing with tensors we'll probably want to be aware of the following attributes
* Shape
* Rank
* Axis or dimension
* Size


In [120]:
def tensor_info(tns):
    print(f'Data type : {tns.dtype}')
    print(f'matrix shape : {tns.shape} ')
    print(f'matrix rank : {tns.ndim} ')
    print(f'matrix size : {tf.size(tns)} ')

In [121]:
# Creat a rank 4 tensor (4dimensions)
rank4_tensor = tf.zeros(shape=(2, 3, 4, 5), dtype=tf.float64)
print(tf.size(rank4_tensor).numpy())
print(tf.size(rank4_tensor))


120
tf.Tensor(120, shape=(), dtype=int32)


#### Squeeze function (removing all signle dimensions) similar to NumPy.squeeze

In [122]:
x = tf.constant([[[0], [1], [2]]])
print(f'x shape : {x.shape}')
print(f'x : \n{x}')
x = tf.squeeze(x, axis=[0, 2])  # select axis to squeeze
# np.squeeze(x, axis=0).shape
# np.squeeze(x, axis=1).shape
print('x : ', x)
tensor_info(x)

x shape : (1, 3, 1)
x : 
[[[0]
  [1]
  [2]]]
x :  tf.Tensor([0 1 2], shape=(3,), dtype=int32)
Data type : <dtype: 'int32'>
matrix shape : (3,) 
matrix rank : 1 
matrix size : 3 


#### Tensorflow reshape

In [123]:
mtx = tf.range(1, 7)
mtx = tf.reshape(mtx, (3, 2))
mtx = tf.reshape(mtx, (2, 3))
mtx

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

## Indexing tensors 

Tensors can be indexed just like Python lists.

In [124]:
# Get the first 2 elements of each dimension
rank4_tensor[:2, :2, :2, :2]
# Get the first elemet of each dimensiopn except the last one
rank4_tensor[:1, :1, :1]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float64, numpy=array([[[[0., 0., 0., 0., 0.]]]])>

In [125]:
# Creat rank 2 tensor (2 dimensions)
rank2_tensor = tf.constant([[1, 2, 3], [4, 5, 6]])
rank2_tensor.shape, rank2_tensor.ndim
rank2_tensor
# Get last element of each dimension
# rank2_tensor[:,-1]

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [126]:
# Add in extra dimension to our rank 2 tensor
rank3_tensor = tf.expand_dims(rank2_tensor, axis=-1)  # expand on the axis passed 
# rank3_tensor = rank2_tensor[..., tf.newaxis] # [...] stands for selecting all dimensions
# rank3_tensor = rank2_tensor[tf.newaxis, ...]
rank3_tensor

<tf.Tensor: shape=(2, 3, 1), dtype=int32, numpy=
array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])>

## Manipulating tensors (tensors operations)

**Basic operations**
`+`, ``-, `*`, `/` 

In [127]:
# you can add value to a tensorusing the addition operator
tensor = tf.constant([[10, 7],
                      [2, 1],
                      [4, 8]])
tensor + 10
# tensor - 10
# tensor / 10
# tensor * 10

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 17],
       [12, 11],
       [14, 18]])>

In [128]:
# We can use the tensorflow built-in function too 
tf.add(tensor, 10)
# tf.subtract(tensor, 10)
# tf.multiply(tensor, 10)
# tf.divide(tensor, 10)


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 17],
       [12, 11],
       [14, 18]])>

## Matrix multiplication

In machine learning, matrix multiplicaation is one of the most common tensor operations

In [129]:
# Matrix multiplication in tensorflow (tf.linalg.matmul)

print(tensor)
# tf.matmul(tensor, tf.transpose(tensor))
tf.matmul(tensor, np.transpose(tensor))
# In numpy transposes are memory-efficient constant time operations as they simply return a new view of the same data with adjusted strides.

# TensorFlow does not support strides, so transpose returns a new tensor with the items permuted

tf.Tensor(
[[10  7]
 [ 2  1]
 [ 4  8]], shape=(3, 2), dtype=int32)


<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[149,  27,  96],
       [ 27,   5,  16],
       [ 96,  16,  80]])>

In [130]:
# Python have the same function with '@' symbol
print(np.transpose(tensor) @ tensor)
print(tensor @ np.transpose(tensor))

tf.Tensor(
[[120 104]
 [104 114]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[149  27  96]
 [ 27   5  16]
 [ 96  16  80]], shape=(3, 3), dtype=int32)


**Difference between reshape and transpose**


In [131]:
print(tensor @ tf.transpose(tensor))
print(tensor @ tf.reshape(tensor,shape=(tf.transpose(tensor).shape)))

tf.Tensor(
[[149  27  96]
 [ 27   5  16]
 [ 96  16  80]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[107  98  76]
 [ 21  18  12]
 [ 48  60  72]], shape=(3, 3), dtype=int32)


In [132]:
print(tensor)
print('tensor reshaped : \n', tf.reshape(tensor,shape=(tf.transpose(tensor).shape)))
print('tensor transposed : \n',tf.transpose(tensor))

tf.Tensor(
[[10  7]
 [ 2  1]
 [ 4  8]], shape=(3, 2), dtype=int32)
tensor reshaped : 
 tf.Tensor(
[[10  7  2]
 [ 1  4  8]], shape=(2, 3), dtype=int32)
tensor transposed : 
 tf.Tensor(
[[10  2  4]
 [ 7  1  8]], shape=(2, 3), dtype=int32)


Generally we use transpose rather than reshape to satisfy multiplication rules

In [133]:
# Elements wise multiplication
tensor * tensor 

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[100,  49],
       [  4,   1],
       [ 16,  64]])>

**The dot product**
Matrix multiplication is also referred to as the dot product.

You can perform matrix mul using :
* `tf.matmul()`
* `tf.tensordot()`

In [134]:
print(tensor)

tf.tensordot(tensor, np.transpose(tensor),axes=1)

tf.Tensor(
[[10  7]
 [ 2  1]
 [ 4  8]], shape=(3, 2), dtype=int32)


<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[149,  27,  96],
       [ 27,   5,  16],
       [ 96,  16,  80]])>

## Changing the datatype of a tensor

**Mixed precision is the use of both 16-bit and 32-bit floating-point types in a model during training to make it run faster and use less memory.**

In [135]:
tf.__version__


'2.10.0'

In [136]:
# Create a new tensor with the default datatype (float32)
B = tf.constant([1.1, 2.3])
B.dtype

tf.float32

In [137]:
C = tf.constant([1, 2])
C.dtype

tf.int32

In [138]:
# Create from float32 to float16 (reduced precision)
D = tf.cast(B, dtype=tf.float16)
D

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.1, 2.3], dtype=float16)>

## Aggreating tensors

Aggregating tensors = condesing them from multiple values to a smaller amount of values.


In [139]:
# Get the absolute values
D  = tf.constant([-7,-10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10])>

In [140]:
# Get the absolut values
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10])>

Following forms of aggregation:

* Get the maximum
* Get the minimum
* Get the mean of a tensor
* Get the sum of a tensor

In [141]:
E = tf.constant(np.random.randint(100,size=(10,10)))
E

<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[87, 16,  2, 34, 82, 76, 85, 33, 42, 44],
       [ 5, 69, 15, 87, 96, 50, 80, 52, 96, 65],
       [40, 65, 81, 50, 43,  2, 57, 95, 97, 66],
       [30, 29, 86, 61, 43, 69, 24, 25, 59, 46],
       [43,  3, 28,  8, 77, 42, 54, 42, 20, 63],
       [37, 24, 95, 71,  1, 97, 54, 54, 44, 16],
       [ 9, 55, 13, 89, 35, 30, 26,  2, 83, 44],
       [10,  8,  5, 72, 50, 91, 95, 65, 27, 12],
       [59, 94, 23, 84, 45, 39, 97, 79, 97, 55],
       [39,  3, 51, 64, 46, 30, 63, 12,  3, 13]])>

In [142]:
tf.reduce_max(E)
tf.reduce_min(E)
tf.reduce_mean(E)
tf.reduce_sum(E)



<tf.Tensor: shape=(), dtype=int32, numpy=4874>

In [143]:
# Manually compute variance of a vector
Var =(tf.subtract(E,tf.reduce_mean(E)))**2
Var=tf.reduce_sum(Var)/100
print('variance : ' , Var)

variance :  tf.Tensor(849.42, shape=(), dtype=float64)


In [144]:
# we need to specify tf.math.... in these functions not as sum,mean....
print(tf.math.reduce_std(tf.cast(E,tf.float32)))
print(tf.math.reduce_variance(tf.cast(E,tf.float32)))

tf.Tensor(29.135414, shape=(), dtype=float32)
tf.Tensor(848.87244, shape=(), dtype=float32)


In [145]:
# Variance and standard  using Tfp
import tensorflow_probability as tfp
 
# E should be float type if we want the accurate float value of variance
print(tfp.stats.stddev(tf.cast(E,tf.float32)))
print(tfp.stats.variance(E))


tf.Tensor(
[23.678892 30.34205  33.762257 24.223955 25.693579 28.545403 24.573359
 27.69278  33.13548  20.382347], shape=(10,), dtype=float32)
tf.Tensor([ 561  921 1140  586  660  815  604  767 1098  415], shape=(10,), dtype=int32)


## Find positional maximum and minimum in a tensor

In [146]:
tf.random.set_seed(42)
F = tf.random.uniform(minval=0,maxval=100,shape=(10,10),dtype=tf.int32)
F

<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[87, 89, 61, 86, 92, 84, 83, 43, 71, 91],
       [52, 40, 51, 81, 20,  8, 59, 32,  9, 99],
       [11, 12, 97, 94, 19,  1, 61, 45,  6, 15],
       [70, 52,  1, 23, 68, 65,  3, 50,  3, 88],
       [52, 38,  1, 19, 92, 54, 82, 79, 39, 36],
       [16, 20, 20, 45, 43, 77, 75, 49,  7,  6],
       [ 9, 78, 82, 36,  4, 19, 39, 95, 85, 18],
       [41, 29, 87, 11, 58, 83, 96, 89, 56, 91],
       [13, 18, 97, 37, 52, 47, 61, 46, 29,  6],
       [25, 19, 80, 13, 72, 85, 35, 26, 72, 19]])>

In [147]:

print(f' argmax among rows : {tf.argmax(F,axis=0)}')
print(f' argmax among cols : {tf.argmax(F,axis=1)}')
print(f' argmin among rows : {tf.argmin(F[2,:],axis=0)}')

 argmax among rows : [0 0 2 2 0 9 7 6 6 1]
 argmax among cols : [4 9 2 9 4 5 7 6 2 5]
 argmin among rows : 5


## One-hot encoding 

In [148]:
# create a list of indices
some_list = [[0,1,2,3,4,5],[2,4,1,5,4,0]]

# one-hot encode our list
tf.one_hot(some_list,depth=6)


<tf.Tensor: shape=(2, 6, 6), dtype=float32, numpy=
array([[[1., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 1.]],

       [[0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0.],
        [0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 1., 0.],
        [1., 0., 0., 0., 0., 0.]]], dtype=float32)>

In [149]:
# One hot encode non numerical values require some preprocessing 

labels = [['green','blue','red'],['green','red','blue']]
labels = np.ravel(labels)
# Get unique categories
unique_labels = set(np.ravel(labels))

# # Create a dictionary mapping labels to indices
label_to_index = {label: i for i, label in enumerate(unique_labels)}
# 
# # Encode labels as indices
encoded_labels = [label_to_index[label] for label in labels]
# 
# # One-hot encode the indices
one_hot_encoded = tf.one_hot(encoded_labels, (len(unique_labels)))

print(one_hot_encoded)

tf.Tensor(
[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]], shape=(6, 3), dtype=float32)


In [150]:
tf.one_hot(some_list,depth=3,on_value=True,off_value=False)

<tf.Tensor: shape=(2, 6, 3), dtype=bool, numpy=
array([[[ True, False, False],
        [False,  True, False],
        [False, False,  True],
        [False, False, False],
        [False, False, False],
        [False, False, False]],

       [[False, False,  True],
        [False, False, False],
        [False,  True, False],
        [False, False, False],
        [False, False, False],
        [ True, False, False]]])>

#### Squaring, log, square root  ...(tf.math operations)

In [151]:
H = tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [152]:
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])>

In [153]:
tf.sqrt(tf.cast(H,tf.float32)) # int values aren't supported so we will get TypeError

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.2360678, 2.4494896,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [154]:
tf.math.log(tf.cast(H,tf.float32)) # it doesn't have an alias that skip '.math'

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

## Tensors and NumPy
Tensorflow interacts smoothly with NumPy (**Full interoperability**)

In [155]:
# Create a tensor directly forma NumPy array
J= tf.constant(np.array([3,7,1]))
J

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([3, 7, 1])>

In [156]:
# Convert a tensor into a numpy array
np.array(J), type(J.numpy())

(array([3, 7, 1]), numpy.ndarray)

In [157]:
# Same as above
J.numpy(), type(J.numpy())

(array([3, 7, 1]), numpy.ndarray)

In [167]:
# The default typer of each are slightly different
numpy_J= tf.constant(np.array([3.,7.,1.]))
tensor_J= tf.constant([3.,7.,1.])
# Check the datatypes of each 
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)